# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'kc-SonarCloud-Connection'
    organization: 'kc-revature-training'
    scannerMode: 'MSBuild'
    projectKey: 'kc-pipeline-project-test'
    extraProperties: |
        sonar.exclusions=**/lib/**

# three different ways to solve the initial problem

# - script:
#     cd RestaurantReviews
#     dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'

# - script: dotnet build RestaurantReviews --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: ./StoreApplication

# - script: dotnet test
#   displayName: dotnet test
#   workingDirectory: RestaurantReviews

# a task can encapsulate some useful logic so we don't have to
# write it all out in script step...
# in this case, this task is both running tests and publishing the results
# to the build itself
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: 'StoreApplication'
    arguments: '-c $(buildConfiguration) --collect "XPlat Code Coverage"'


- task: SonarCloudAnalyze@1
  displayName: Run SonarCloud analysis

- task: SonarCloudPublish@1
  displayName: Publish SonarCloud quality gate result
  inputs:
    pollingTimeoutSec: '300'

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(1)(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
    appType: 'webApp'
    WebAppName: 'GeneralNonsense'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

